const menuList = [
    {
        title:'首页',
        key:'/main/home'
    },
    {
        title:'UI',
        key:'/ui',
        children:[
            {
                title:'按钮',
                key:'/main/ui/buttons',
            },
            {
                title:'弹框',
                key:'/main/ui/modals',
            },
            {
                title:'加载',
                key:'/main/ui/loadings',
            },
            {
                title:'通知提醒',
                key:'/main/ui/notification',
            },
            {
                title:'全局消息',
                key:'/main/ui/messages',
            },
            {
                title:'页签',
                key:'/main/ui/tabs',
            },
            {
                title:'图片画廊',
                key:'/main/ui/gallery',
            },
            {
                title:'轮播图',
                key:'/main/ui/carousel',
            }
        ]
    },
    {
        title:'表单',
        key:'/form',
        children:[
            {
                title:'登录',
                key:'/main/form/login',
            },
            {
                title:'表单注册',
                key:'/main/form/form-reg',
            },{
                title:'步骤注册',
                key:'/main/form/steps-reg',
            }
        ]
    },
    {
        title:'表格',
        key:'/table',
        children:[
            {
                title:'基础表格',
                key:'/table/basic',
            },
            {
                title:'高级表格',
                key:'/table/high',
            }
        ]
    },
    {
        title:'富文本',
        key:'/rich',
        children:[
            {
                title:'基础文本',
                key:'/rich/basic',
            }
        ]
    },
    {
        title:'城市管理',
        key:'/city',
        children:[
            {
                title:'城市地图',
                key:'/city/basic',
            }
        ]
    },
    {
        title:'订单管理',
        key:'/order',
        children:[
            {
                title:'订单详情',
                key:'/order/detail'
            },
            {
                title:'结束订单',
                key:'/order/finish'
            }
        ]
    },
    {
        title:'员工管理',
        key:'/user',
        children:[
            {
                title:'员工管理',
                key:'/user/base'
            },
            {
                title:'公告信息',
                key:'/user/all'
            }
        ]
    },
    {
        title:'车辆地图',
        key:'/bikeMap',
        children:[
            {
                title:'地图分布',
                key:'/bikeMap/base'
            }
        ]
    },
    {
        title:'图标',
        key:'/charts',
        children:[
            {
                title:'柱形图',
                key:'/charts/bar'
            },
            {
                title:'饼图',
                key:'/charts/pie'
            },
            {
                title:'折线图',
                key:'/charts/line'
            },
        ]
    },
    {
        title:'权限设置',
        key:'/permission',
        children:[
            {
                title:'角色管理',
                key:'/permission/role'
            },
            {
                title:'菜单管理',
                key:'/permission/function'
            }
        ]

    },
];
export default menuList;